(function(z){
var xL=function(a,b,c){b="new"===(b||a.md);return c?(a=a.d.u.v().get(z.U.Fp),b?-1:-a):a.cl+(b?-1:1)};var yL=function(a){z.Yv.call(this,a);this.cl=0;this.md="new"};var zL=function(a,b){a.MX=b};
var AL=function(a){return(0,z.Q)('\x3cdiv class\x3d"fyre '+(a.Gd?"fyre-liveblog ":"")+(a.bh?"fyre-livechat ":"")+(a.gU?"fyre-bootstrap ":"")+(a.re?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Sa?"fyre-avatar-disabled":"")+'"\x3e'+(a.Av?z.Mo(z.Ws(a)):"")+(0,z.Q)('\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e')+'\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Sa?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.ro?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var BL=function(a){return(0,z.Q)('\x3ca href\x3d"'+z.R(z.S(a.Ea))+'" title\x3d"'+z.R(a.ba)+'" data-id\x3d"'+z.R(a.id)+'" class\x3d"fyre-follower fyre-follower-'+z.R(a.OT)+'"\x3e\x3cimg src\x3d"'+z.R(z.S(a.xd))+'" alt\x3d"'+z.R(a.ba)+'" onerror\x3d"javascript:this.src\x3d\''+z.R(z.fp(a.ac))+"';\" /\x3e\x3c/a\x3e")};
var CL=function(a){return(0,z.Q)(z.fr(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+z.P(a.j.jO)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.P(a.j.Yx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(a.j.Wo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.P(a.j.Zx)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e")};var DL=function(a){return(0,z.Q)('\x3cdiv class\x3d"tooltip"\x3e'+z.P(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e')};var EL=function(){};var FL=function(a){this.FG=!1;this.Lo=[];this.zb=null;z.Gf.call(this,a)};var GL=function(a,b){z.Hj.call(this,b,a)};var HL=function(a,b){z.oG.call(this,a,b)};
var IL=function(a,b){var c=a.d.Jb;c.oh[4]&&(z.xz(c,4,(0,z.r)(function(a){b.e(a,"threadBreakout",this.Mr)},a)),z.zz(c,4,(0,z.r)(function(a){b.Ia(a,"threadBreakout",this.Mr)})))};var JL=function(a,b){var c=[a.nm,a.tz];a.wg&&c.push(a.wg);a.pt&&c.push(a.pt);a.uz&&c.push(a.uz);z.x(c,function(a){z.lk(a,"fyre-stream-sort-selected")});z.ik(b,"fyre-stream-sort-selected")};var KL=function(a,b){z.oG.call(this,a,b)};
var LL=function(a,b){z.$x.call(this,a,b);this.ah=!1;this.NI=!!this.C.J.IG;this.Ga=new z.iy;this.Ga.rc(this);this.qu="archiveShowMore"};var ML=function(a,b){z.lG.call(this,a,b)};var NL=function(a,b,c){z.mu.call(this,a,b,c);this.Pz=b||"";this.tg(DL(this.s()))};var OL=function(a,b,c){z.gu.call(this,a,b||3,c)};var PL=function(a,b){z.T.call(this,b);this.l=a};var QL=function(a,b){z.T.call(this,b);this.Cc=a};var RL=function(a,b){QL.call(this,a,b)};
var SL=function(){var a=z.t.window,b=z.t.document;function c(){var a=v.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){v.qX||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,
function(a){b[a]=d(a);g.createElement(a);return'c("'+a+'")'})+");return n}")(v,g)}function f(a){var b;if(a.uP)return a;if(v.pX&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";
b=!!c.insertBefore(b.lastChild,c.firstChild)}q||(b=!d(a));b&&(a.uP=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,q;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.bU&&a.bU("#modernizr{}",function(b){b.hidden=
!0;m="none"==(a.getComputedStyle?a.getComputedStyle(b,null):b.currentStyle).display});q=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var v={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:!1!==g.pX,shivMethods:!1!==g.qX,type:"default",shivDocument:f};f(b)};var TL=function(a,b){z.wG.call(this,a,b);a.J.oP||SL();var c=a.u.Bc(),d=a.u.v();this.ki=new z.mG(a,a.Ol.wa,d.bh()||z.eg);this.F(this.ki);a.J.Sa||(this.Fn=new RL(c),this.F(this.Fn));this.Tr=new z.kG;this.F(this.Tr)};
var UL=function(a,b){var c=b.getBoundingClientRect(),d=c.top,f=.6*c.height,g=0,h=null,k=a.o(VL),m=new z.Cz(function(){var q=a.o(WL);if(""===q.style.display||"block"===q.style.display)b=q;c=b.getBoundingClientRect();d=c.top;f=.6*c.height;(0,window.clearTimeout)(g);g=(0,window.setTimeout)(function(){window.innerHeight-f>=d&&Math.abs(k.getBoundingClientRect().top)<=k.getBoundingClientRect().height&&(a.d.Tb.send(z.bo("View")),z.al(h),(0,window.clearTimeout)(g),g=null,m.p())},1E3)},100),h=z.Pk(window,
"scroll",function(){m.Dn()});m.Dn()};var XL=function(a){var b=z.E.kb()||z.E.get(z.D.Hp);return!a.w.Gd()||b};var YL=function(a){z.Gz.call(this,a);this.Um=1};var ZL=function(a){z.Zs.call(this,a);z.zv(a.u);this.Sb=new TL(a);this.Zq.start();this.El(this.Sb);z.dt(this)};var $L=function(a,b){this.dD=GL;this.SJ=ZL;z.X.$o(b.strings||{});z.Mn.call(this,a,b);this.vb.Tb.send(z.bo("Init"))};var aM=function(a){a.qk&&(a.qk.p(),delete a.qk)};z.u(yL,z.Yv);z.e=yL.prototype;z.e.ql=z.l(60);z.e.IF=z.l(62);z.e.JF=z.l(61);
z.e.IF=z.K(62,function(a){this.La||(this.Ho[a]=!1,z.Zv(this,a,function(a){a.N(a.ya.Tm)}))});
z.e.JF=z.K(61,function(a,b){if(!this.La){var c=this.d.u.v(),d=z.Tu(a,b),f=c.get(z.U.Mt);c.set(z.U.Fp,d.tV);z.y(d.ab,(0,z.r)(this.d.U.N,this.d.U,"bootstrap_author_received"));d.content=z.jj(d.content,function(a,b){return!z.Ua(f,b)});z.y(d.content,function(a){z.lb(d.content,z.aw(this,a))},this);z.lb(this.qc,z.ij(d.content,z.Eb(a)));this.$d(a,d.content);z.Zv(this,a,function(b){b.N(b.ya.Gk,{Kd:a});b.set(b.k.mf,!0)})}});
z.e.ql=z.K(60,function(a,b){this.cl=a;this.md=b||this.md;var c=this.Ld[a]=new z.Uv;z.ov.D();var d=this.d.u.v(),f=(0,z.r)(this.JF,this,a),g=(0,z.r)(this.IF,this,a),h=this.d.J.Zm,d=d.get(z.U.vc),h=z.w.Uu(d,h)+String(a)+".json";z.pv(0,h,f,g);return c});z.SG.prototype.ql=z.K(59,function(a,b){this.Pk||(this.Pk=new yL(this.C));var c=this.Pk,d=xL(c,a,b);return c.ql(d,a)});z.ov.prototype.Th=z.K(51,function(a,b,c){a=z.wa("%s%scollection/%s/hot/",z.w.K.fe,z.w.jf,a.na);(new z.Qe({url:a,xa:b,sa:c})).send()});
z.ow.prototype.Th=z.K(50,function(a){var b={na:this.d.u.v().id},c=z.ov.D().Th;z.pw(this,c,b,a);return a});z.SG.prototype.Th=z.K(49,function(){z.uw(this);this.Mi=new z.ow(this.C,void 0);var a=new z.Uv;this.Mi.Th(a);return a});z.ov.prototype.Ph=z.K(48,function(a,b,c){a=z.wa("%s%scollection/%s/top/%s/",z.w.K.fe,z.w.jf,a.na,a.dO);(new z.Qe({url:a,xa:b,sa:c})).send({format:"stream"})});z.ow.prototype.Ph=z.K(47,function(a,b){var c={na:this.d.u.v().id,dO:a},d=z.ov.D().Ph;z.pw(this,d,c,b);return b});
z.SG.prototype.Ph=z.K(46,function(a){z.uw(this);this.Mi=new z.ow(this.C,void 0);var b=new z.Uv;this.Mi.Ph(a,b);return b});z.T.prototype.UG=z.K(45,function(){return this.Y});z.Ej.prototype.ro=z.K(44,function(){return this.get(this.k.Ep)});z.u(EL,z.Sn);z.ca(EL);var bM={QY:"attachmentDelegate"};z.lb(bM,z.jH);EL.prototype.oo=function(a){var b=EL.b.oo.call(this,a),c=a.attachmentDelegate;c&&(b.mO=c);b.Sx=a[bM.WL]||null;return b};z.u(FL,z.Gf);FL.prototype.DU=function(a){this.zb||(this.zb=z.t.setInterval((0,z.r)(this.tQ,this),5E3));this.Lo=this.Lo.concat(a)};
FL.prototype.tQ=function(){this.Lo.length&&(this.FG||(z.vc("//platform.twitter.com/impressions.js"),this.FG=!0),z.t.twttr=function(){var a=z.t.twttr||{},b=a.impressions||{};b._e=b._e||[];b.ready=b.ready||function(a){b._e.push(a)};a.impressions=b;return a}(),z.t.twttr.impressions.ready((0,z.r)(function(a){a.impressions.logTweets(this.Lo,{partner:"livefyre"});this.Lo=[]},this)))};FL.prototype.p=function(){(0,window.clearInterval)(this.zb);FL.b.p.call(this)};z.u(GL,z.Hj);GL.prototype.ez=function(a){this.Hi=new z.jv(this);this.Bu=new z.Wq(this,a);this.Kc=new z.xi(this);this.gb=new z.Iv(this,a);this.Ol=new z.Qv(this);this.u=new z.xv(this,a);this.Mb=new z.SG(this,a);new z.rf;this.cp=new z.Iw(this,a);this.Bz=new z.vw(this);this.gY=new FL(this);this.Tb=new z.Un(this);this.Jb=new z.nz(this)};z.u(HL,z.oG);z.e=HL.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.Nx=b.v().Gd();a.qV=!z.E.get(z.E.k.Vd);a.Fd=b.Fd(z.E.id);a.rP=2===c.get(z.U.$i);a.qP=3===c.get(z.U.$i);a.j={wU:z.X.get(z.X.g.du),zU:z.X.get(z.X.g.eu),MT:z.X.get(z.X.g.jB),Yx:z.X.get(z.X.g.Zp),Zx:z.X.get(z.X.g.$p),Wo:z.X.get(z.X.g.kC),mp:z.X.get(z.X.g.dq),$X:z.X.get(z.X.g.CC)};return a};
z.e.L=function(a){HL.b.L.call(this,a);a=this.c;var b;b=this.s();var c=z.Q,d=z.fr(b),f;f=b.Nx?(0,z.Q)('\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.qV?b.Fd?z.P(b.j.zU):z.P(b.j.wU):"")+"\x3c/a\x3e"):"";b=c(d+f+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.P(b.j.Yx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Wo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.P(b.j.Zx)+"\x3c/a\x3e"+(b.rP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Wo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+z.P(b.j.$X)+"\x3c/a\x3e":"")+(b.qP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Wo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+z.P(b.j.MT)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e');a.innerHTML=b;this.pl=this.o("fyre-follow-conversation");this.pt=this.o("fyre-stream-sort-hot-threads")||
null;this.uz=this.o("fyre-stream-sort-top-comments")||null;this.wg=this.o("fyre-stream-sort-back");this.nm=this.o("fyre-stream-sort-newest");this.tz=this.o("fyre-stream-sort-oldest");this.TI=this.o("fyre-stream-sort-options");this.Zc=this.o("fyre-content-loading");this.Ed()};z.e.m=function(){HL.b.m.call(this);var a=this.q();z.E.on(z.E.ya.Tf,this.ho,this);a.e(this.c,"click",this.jb);z.x([3,4,5],function(b){z.pG(this,a,b)},this);IL(this,a)};
z.e.jb=function(a){a.preventDefault();a=a.target;if(!z.pk(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.wg)if(a===this.pl)this.GF();else switch(JL(this,a),this.mm(),a){case this.pt:this.rE();break;case this.uz:this.dispatchEvent({type:"sortTopComments",Xb:(0,z.r)(this.Ed,this)});break;case this.nm:this.tn("new");break;case this.tz:this.tn("old")}};z.e.Di=function(a,b){a&&this.fz(b);z.Bl(this.TI,"display",a?"none":"block");z.Bl(this.wg,"display",a?"block":"none")};
z.e.fz=function(a){var b=this.nm,c=this.tn,d=z.X.get(z.X.g.Nt);4===a&&(b=this.pt,c=this.rE,d=z.X.get(z.X.g.fK));this.wg.innerHTML=d;this.q().Hd(this.wg,"click",(0,z.r)(function(a){a.stopPropagation();this.Di(!1);JL(this,b);c.apply(this)},this))};z.e.bo=function(a){a.stopPropagation();this.Di(!1);JL(this,this.nm);this.tn()};z.e.Mr=function(a){var b=a.Xb;z.lb(a,{Xb:(0,z.r)(function(){b();this.Di(!0,4)},this)})};
z.e.tn=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Xb:(0,z.r)(this.Ed,this)})};z.e.rE=function(){this.dispatchEvent({type:"sortHotThreads",Xb:(0,z.r)(this.Ed,this)})};z.e.GF=function(){var a=this.d.u;a.v();var b=z.E.k;z.E.id?(b=a.Fd(z.E.get(b.W)),a.yj(!b),a=b?z.X.get(z.X.g.du):z.X.get(z.X.g.eu),this.pl.innerHTML=a):z.Sh(this.d.Kc,(0,z.r)(this.GF,this))};
z.e.ho=function(){var a=this.d.u,b=a.v(),c=z.E.k,b=!b.Gd()||z.E.get(c.Vd);this.pl&&(b?z.N(this.pl,!1):(a=a.Fd(z.E.id)?z.X.get(z.X.g.eu):z.X.get(z.X.g.du),this.pl.innerHTML=a,z.N(this.pl,!0)))};z.e.h=function(){HL.b.h.call(this);z.E.off(null,null,this)};z.u(KL,HL);KL.prototype.L=function(a){this.c=a;z.yo(a,CL,this.s());this.nm=this.o("fyre-stream-sort-newest");this.tz=this.o("fyre-stream-sort-oldest");this.TI=this.o("fyre-stream-sort-options");this.Zc=this.o("fyre-content-loading");this.Ed()};KL.prototype.tn=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",stream:this.MX.stream,direction:a,Xb:(0,z.r)(this.Ed,this)})};
KL.prototype.s=function(){return{j:{jO:z.X.get(z.X.g.aK),Yx:z.X.get(z.X.g.Zp),Zx:z.X.get(z.X.g.$p),Wo:z.X.get(z.X.g.kC),mp:z.X.get(z.X.g.dq)}}};z.u(LL,z.$x);z.e=LL.prototype;z.e.gn=function(a){this.clear();z.N(this.c,!0);this.md=a};z.e.clear=function(){this.kd.Kf();this.Ab={};this.Fj=[];for(this.ph=this.Tk=null;this.ma&&0!=this.ma.length;)this.Oo(0).p()};z.e.L=function(a){LL.b.L.call(this,a);z.yo(this.c,z.gr,this.s());this.ik=this.o("fyre-stream-content");this.Ei=this.o("fyre-stream-more");this.Ga.S(this.Ei);z.N(this.Ei,!1)};z.e.h=function(){this.Ga&&this.Ga.p();this.Ga=null;LL.b.h.call(this)};
z.e.m=function(){LL.b.m.call(this);this.q().e(this.Ga,"showMore",this.Xw)};z.e.aw=function(){return this.C.J.IG};z.e.s=function(){return{ae:z.w.K.nb,tv:!!this.Ga,j:{lz:z.X.get(z.X.g.bK)}}};z.e.Yw=function(){this.Ga.kt();this.ah=!0};z.e.py=function(){this.dispatchEvent({type:this.qu,direction:this.md,target:this,oY:this.ah&&this.NI,Xb:(0,z.r)(this.Yw,this),xj:(0,z.r)(this.fG,this)});this.ah&&(this.NI=!1)};z.e.wy=function(a){this.ah||LL.b.wy.call(this,a)};
z.e.bp=function(){var a=this.C.Mb.Pk,b=this.md,c=a.d.u.v(),b="old"===b,c=c.get(z.U.Fp),c=!b&&a.cl>-c;b&&-1>a.cl||c?this.Ga.show():this.Ga.qb()};z.e.start=function(){this.ah||this.py()};z.u(ML,z.lG);var cM=z.X.g,dM={};dM.comment=[cM.Om,cM.Uf,cM.Cm];dM.liveblog=[cM.yM,cM.KL,cM.pB];ML.prototype.cF=function(a){function b(a){return z.Ga(a,"%s")?a:"%s "+a}var c=this.l.Gd()?"liveblog":"comment",c=dM[c];switch(a){case 1:c=b(z.X.get(c[1]));break;case 0:if(z.X.get(c[0])!==z.jG[c[0]]){c=z.X.get(c[0]);break}default:c=b(z.X.get(c[2]))}return z.wa(c,a)};z.u(NL,z.mu);NL.prototype.ep=200;NL.prototype.Vh=function(){return new OL(this.Jc)};NL.prototype.s=function(){var a={};a.message=this.Pz;return a};z.u(OL,z.gu);OL.prototype.Oc=function(a,b,c){var d=z.$l(this.element),d=new z.Ch(d.width,d.height+25);b=z.bu(this.element,this.Ih,a,b,d,c,9);z.Hl(a.lastChild,0);b&&(d=new z.Ch(0,-5),z.bu(this.element,2,a,1,d,c,5),z.Hl(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};z.u(PL,z.T);z.e=PL.prototype;z.e.r=function(){this.c=z.Bo(BL,this.s())};z.e.m=function(){PL.b.m.call(this);this.Va=new NL(this.c,this.l.get("displayName"));this.q().e(this.c,"click",this.jb)};z.e.h=function(){PL.b.h.call(this);this.Va&&this.Va.p()};z.e.s=function(){var a=z.Wd,b={};b.xd=this.l.get(a.xb);b.ac=this.l.get(a.wk);b.ba=this.l.get(a.ua);b.id=this.l.id;b.OT=this.l.id.replace(/[@.]/g,"-");b.Ea=this.l.get(a.Zb);return b};
z.e.jb=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.l,type:"author_click"})};z.u(QL,z.T);z.e=QL.prototype;z.e.tB=10;z.e.h=function(){QL.b.h.call(this);delete this.Cc};z.e.Q=function(){QL.b.Q.call(this);this.Cc.off(null,null,this)};z.e.qF=function(a){a=new PL(a);var b=this.Mc();if(b===this.tB){var c=this.Oo(b-1);c&&(c.p(),b--)}0<b?this.Ge(a,0,!0):this.F(a,!0)};z.e.TS=function(a){var b;this.Uc(function(c){a.id===c.l.id&&(b=c)});b&&(this.removeChild(b),b.p())};
z.e.co=function(){this.Cc.on(this.Cc.ya.Lt,this.qF,this);this.Cc.on(this.Cc.ya.mu,this.TS,this);var a=this.Cc.rb.reverse().slice(0,this.tB);z.x(a,this.qF,this)};z.u(RL,QL);var VL,WL;z.u(TL,z.wG);
TL.prototype.jI=function(a,b){if(!this.La){this.w=b;var c=b.get(z.U.yh),d=b.get(z.U.Xd);this.Ft=new z.tG(c,d,a.J.Sa);this.F(this.Ft);this.Jq=new ML(a.u.v());this.F(this.Jq);this.xs=null;b.ro()&&(this.Mu=new KL(a),this.F(this.Mu),this.Qk=new LL(a),this.F(this.Qk),zL(this.Mu,{stream:this.Qk}));this.mh=new HL(a);this.F(this.mh);this.ps((0,z.r)(function(a){this.bc=a;this.F(this.bc);a=this.bc;this.Y&&a&&a.S(this.Bd,!0)},this));b.get(z.U.Im)&&!z.eg&&this.w.gr()&&(this.w.bh()||this.w.Gd()||this.Dw())}};
TL.prototype.s=function(){var a=!this.d.J.zq&&!z.w.rv&&!this.d.J.nE;return{qJ:z.w.K.Rz,rJ:(0,window.encodeURIComponent)(String(window.location.href)),Sa:this.d.J.Sa,bh:this.w.bh(),Gd:this.w.Gd(),re:z.eg,Av:a,gU:this.d.J.zq,ro:this.w.ro()}};VL="fyre-widget";WL="fyre-featured-content-wrapper";z.oy={MY:"fyre-archive-stream",NY:"fyre-archive-stream-header",B1:"fyre-top-content-stream",V1:VL,Im:WL};z.lb(z.oy,z.iK);z.e=TL.prototype;
z.e.r=function(){this.c=z.Bo(AL,this.s());var a=this.w.get(z.U.$i);if(1!==a){var b=this.d.Jb,a=2===a?3:4,c=this.o("fyre-top-content-stream");z.oz(b,a,c,this)}this.Tr.S(this.o(z.oy.vL));this.Qk&&(b=this.o("fyre-archive-stream-header"),this.Mu.S(b),this.Qk.S(this.o("fyre-archive-stream")));this.Jh(1);this.Bd=this.o(z.oy.vh);b=XL(this);z.N(this.Bd,b)};
z.e.m=function(){TL.b.m.call(this);var a=this.bc;this.Y&&a&&a.S(this.Bd,!0);UL(this,this.Bd);this.d.U.op("stream_data_received",this.RR,this);this.q().e(this,"request_content_context",this.oR).e(this,"request_content_reply",this.WS);this.Qk&&this.Qk.start()};z.e.co=function(){this.Fn&&this.Fn.co()};z.e.RR=function(){var a=this.w,b=a.get(z.U.Ak);z.th||b||(b=(0,z.r)(function(){this.xs=new z.eM(this.d,a.get(z.U.Xd));this.F(this.xs,!0)},this),z.vc(z.w.K.nb+z.w.Ff.xs,null,null,b))};
z.e.Dw=function(){var a=new z.cF(this.UG,this);a.KH=(0,z.r)(this.LW,this);var b=(0,z.r)(function(){a.start(0,2E3)},this);z.vc(z.w.K.nb+z.w.Ff.XP,null,null,b)};z.e.LW=function(){var a=this.o(WL);this.Nv=new z.yK(this.d);this.F(this.Nv);this.Nv.S(a);this.Nv.$g()};z.e.ps=function(a){if(!this.d.J.readOnly){var b=this.d.u.v();z.cx(z.$w.D(),"main",a,{C:this.d,vi:"new"},b);z.E.on(z.E.kc(z.E.k.W),this.Vc,this)}};z.e.Vc=function(){if(this.Bd){var a=XL(this);z.N(this.Bd,a)}};
z.e.$h=function(){0<z.Hp(this,this.bc)&&(this.removeChild(this.bc),this.bc.p());this.ps((0,z.r)(function(a){this.bc=a;this.F(this.bc);a=this.bc;this.Y&&a&&a.S(this.Bd,!0);z.N(this.Bd,!0)},this))};z.e.Zg=function(a,b){null!=a&&(this.d.Jb.ul(1),(0,window.setTimeout)((0,z.r)(function(){var c=b&&function(a){z.Zw(a.eb)};this.La||z.xG(this,a,c)},this),3E3))};z.e.oR=function(a){z.xG(this,a.Yk)};z.e.WS=function(a){z.xG(this,a.Yk,function(a){z.Zw(a.eb)})};
z.e.h=function(){TL.b.h.call(this);z.E.off(z.E.kc(z.E.k.W),this.Vc,this);this.w&&(this.w.off(null,null,this),this.w=null)};z.u(YL,z.Gz);z.e=YL.prototype;z.e.ne=function(a,b){YL.b.ne.call(this,a,b);a.e(b,"repliesExpanded",this.DF);a.e(b,"sortHotThreads",this.fT);a.e(b,"sortOrderChanged",this.iG);a.e(b,"sortTopComments",this.gT);a.e(b,"archiveShowMore",this.YQ);a.e(b,"archiveSortOrderChanged",this.ZQ)};
z.e.YQ=function(a){var b=a.Xb||z.n,c=(0,z.r)(this.Se,this,a.target),d=this.d.Mb;a=a.oY;d.Pk||(d.Pk=new yL(d.C));d=d.Pk;a=a?d.cl:xL(d);var f=d.$c[a];f&&(d.cl=a);if(f)b(),c(f);else{d=this.d.Mb.ql();a=d.k.mf;if(d.get(a))b();else d.on(d.kc(a),b,this);z.Hz(this,d,c)}};z.e.yw=function(a,b){var c=2===b.bd,d=1!==b.bd;switch(b.type){case 0:var f=this.d.u.v(),f=z.Lm(b,f),g=f.get(z.$m),g=this.d.u.ab().get(g);f.set(z.Mm,g);a.Pw(f,c,d)}};
z.e.aG=function(a){if(1!==this.Um){var b=this.EX.mh;b.Di(!1);JL(b,b.nm);z.lb(a,{direction:"new",Xb:z.n});this.iG(a)}};z.e.ZQ=function(a){z.Iz(this);a.stream.gn(a.direction);var b=this.d.Mb.ql(a.direction,!0),c=(0,z.r)(function(b){a.Xb();this.Se(a.stream,b)},this);z.Hz(this,b,c,a.xj)};z.e.iG=function(a){this.d.J.ei=null;var b=z.Kz(this,1);z.uw(this.d.Mb);b.gn(a.direction);var c=z.tw(this.d.Mb,a.direction),d=(0,z.r)(function(c){a.Xb();this.Se(b,c)},this);z.Hz(this,c,d,a.xj)};
z.e.gT=function(a){var b=z.Kz(this,3),c=this.d.Mb.Ph("likes");z.Hz(this,c,(0,z.r)(function(c){a.Xb();z.ib(c)?z.Zx(b):this.Se(b,c)},this))};z.e.fT=function(a){var b=z.Kz(this,4),c=this.d.Mb.Th();z.Hz(this,c,(0,z.r)(function(c){a.Xb();z.ib(c)?z.Zx(b):this.Se(b,c)},this))};z.u(ZL,z.Zs);z.e=ZL.prototype;z.e.c=null;z.e.h=function(){ZL.b.h.call(this);this.rt.p();this.FD.p();this.Sb.Y&&this.Sb.p();this.Sf&&this.Sf.p();delete this.Sf};z.e.El=function(a){ZL.b.El.call(this,a);this.rt=new YL(this.d);this.rt.handle(a);this.FD=new z.Dz(this.d);this.FD.handle(a)};z.e.Cz=function(){this.d.Hi.stop()};z.e.LX=function(){this.d.Ol.stop()};z.e.fk=function(){this.d.Hi.start()};z.e.IX=function(){this.d.Ol.start()};
z.e.pa=function(){this.Sf&&this.Sf.p();this.Sb.pa(this.c);this.d.Tb.send(z.bo("Load"));var a=z.at(window.location,"reply_editor");if("object"===typeof window.Livefyre&&window.Livefyre.WN)z.et(this,a);else{var b=z.bt(this);this.Sb.Zg(b,a)}this.d.U.N("render_complete",this.c)};z.u($L,z.Mn);$L.prototype.ZC=EL.D();$L.prototype.h=function(){$L.b.h.call(this);this.stop();delete this.J;delete this.ha;aM(this);z.Rn(this);this.wj&&(this.wj.p(),delete this.wj)};$L.prototype.Kz=function(){this.stop();aM(this);$L.b.Kz.call(this)};z.mg.main.Lh.ia($L);})(fyre.conv);
