function bindWelcome(){$(document).ready(function(){var wm=$("#WelcomeModule");var currentDate=new Date();var expirationDate=new Date(currentDate.getFullYear(),currentDate.getMonth(),currentDate.getDate(),23,59,59);$.cookie("st_welcome","viewed",{path:'/',expires:expirationDate,domain:'.startribune.com'});wm.click(function(e){var link=$(this).attr('href');if(!(link===undefined||link===null)&&link!="#comments"&&link.length>0){e.preventDefault();var windowFeatures="status=no,height=300,width=500,toolbar=no,menubar=no,scrollbars=no,location=no,directories=no";window.open(link,'sharer',windowFeatures);}});});}
function closeWelcome(){document.body.scrollTop=document.documentElement.scrollTop=0;document.getElementById("WelcomeModule").style.display='none';}
function resizeWelcome(){try{var welcomeInfoBox=document.getElementById('welcome-info');var welcomePhoto=document.getElementById('welcome-photo-img');var adPadding=95,adHeight=90,infoWidth=395,infoHeight=welcomeInfoBox.offsetHeight,oldWindowHeight=0,oldWindowWidth=0;var maxHeight=window.innerHeight- adHeight- adPadding;var maxWidth=document.documentElement.clientWidth- infoWidth;if(maxWidth>970){maxWidth=970;}
welcomePhoto.style.maxHeight=maxHeight+'px';welcomePhoto.style.maxWidth=maxWidth+'px';var topMargin=0;var ofh=welcomePhoto.offsetHeight;if(ofh!==0&&maxHeight>ofh){var topMarginHold=(maxHeight- ofh)/ 2;
topMargin=topMarginHold;}
welcomePhoto.style.marginTop=topMargin+'px';welcomeInfoBox.style.marginTop=((infoHeight/2)*-1)+'px';}catch(exception){}}
function resizeWelcomeSafari(){try{var welcomeInfoBox=document.getElementById('welcome-info');var welcomePhoto=document.getElementById('welcome-photo-img');var adPadding=95,adHeight=90,infoWidth=395,infoHeight=welcomeInfoBox.offsetHeight,oldWindowHeight=0,oldWindowWidth=0;var maxHeight=window.innerHeight- adHeight- adPadding;var maxWidth=document.documentElement.clientWidth- infoWidth;if(maxWidth>970){maxWidth=970;}
welcomePhoto.style.maxHeight=maxHeight+'px';welcomePhoto.style.maxWidth=maxWidth+'px';var topMargin=0;var ofh=welcomePhoto.offsetHeight;if(ofh>0){if(maxHeight>ofh){var topMarginHold=(maxHeight- ofh)/ 2;
topMargin=topMarginHold;}
welcomePhoto.style.marginTop=topMargin+'px';welcomeInfoBox.style.marginTop=((infoHeight/2)*-1)+'px';}else{setTimeout(resizeWelcome,20);setTimeout(resizeWelcome,500);}}catch(exception){}}
function populateWelcome(){document.getElementById("WelcomeModule").style.display='block';document.getElementById("welcome-close").onclick=closeWelcome;setTimeout(closeWelcome,12000);if(navigator.userAgent.indexOf('Safari')!=-1&&navigator.userAgent.indexOf('Chrome')==-1){resizeWelcomeSafari();}else{resizeWelcome();}
window.addEventListener('orientationchange',resizeWelcome);AddWelcomeAd();bindWelcome();}