var ST_Share=(function($,window){var module={'tag':'.st-share-link','elements':[]};$(module.tag).on('click',function(e){var service=module.getAttr(this,'st-share-service');var data=module.extractData(service,this);var link=module.getUrl(service,data);var url=module.checkForUrl(this);if(typeof url=='string'&&url.indexOf("#comments")==-1&&url.length>0){e.preventDefault();var windowFeatures="status=no,height=300,width=500,toolbar=no,menubar=no,scrollbars=no,location=no,directories=no";window.open(link,'sharer',windowFeatures);}});module.init=function(){$(module.tag).each(function(){module.initSocialCount(this);module.setShareLink(this);});};module.initCounts=function(){$(module.tag).each(function(){module.initSocialCount(this);});};module.initSocialCount=function(that){var url=module.getAttr(that,'st-count-url');var service=module.getAttr(that,'st-share-service');if(typeof url!='string'||module.varEmpty(url)){url=module.checkForUrl(that);}
var queryUrl=module.getCountQueryUrl(service,url);module.elements[queryUrl]=that;module.query(queryUrl);};module.initShareLinks=function(){$(module.tag).each(function(){module.setShareLink(this);});};module.setShareLink=function(that){var service=module.getAttr(that,'st-share-service');var data=module.extractData(service,that);var url=module.getUrl(service,data);$(that).attr('href',url);};module.setCount=function(fetchedCount,countSelector){var count=0;if(typeof fetchedCount=='number'||typeof fetchedCount=='string'){count=fetchedCount;}
if(countSelector!=''){$(countSelector).html(count);}};module.handleResult=function(result,url){var count=0;var element=module.elements[url];var countSelector=module.getAttr(element,'st-share-count-selector');if(result.hasOwnProperty('count')){count=result.count;}
if(typeof result=='object'&&typeof result[0]=='object'&&result[0].hasOwnProperty('total_count')&&typeof result[0].total_count=='number'){count=result[0].total_count;}
return module.setCount(count,countSelector);};module.query=function(url){if(typeof url=='string'){$.ajax({url:url,success:function(response){return module.handleResult(response,url);},dataType:"jsonp",crossDomain:true});}};module.addQueryStrings=function(obj){var queryString={};for(var key in obj){if(obj.hasOwnProperty(key)&&obj[key]!=''){queryString[key]=obj[key];}}
return $.param(queryString);};module.getAttr=function(that,dataAttr){if($(that).data(dataAttr)){return $(that).data(dataAttr);}
if($(that).attr(dataAttr)){return $(that).attr(dataAttr);}
return'';};module.varEmpty=function(value){return(value=='');};module.checkForUrl=function(that){var url=module.getAttr(that,'st-share-url');if(module.varEmpty(url)){url=module.getAttr(that,'st-count-url')}
if(module.varEmpty(url)){return window.location.href;}
return url;};module.checkMethod=function(service,string,data){if(module.hasOwnProperty(service)&&module[service].hasOwnProperty(string)){return module[service][string](data);}};module.getCountQueryUrl=function(service,url){return module.checkMethod(service,'getCount',url);};module.extractData=function(service,that){return module.checkMethod(service,'extract',that);};module.getUrl=function(service,data){return module.checkMethod(service,'getUrl',data);};module.extractUrl=function(that){return{'url':module.checkForUrl(that)};};module.facebook={extract:module.extractUrl,getUrl:function(data){return'https://www.facebook.com/sharer/sharer.php?'+ module.addQueryStrings({'u':data.url});},getCount:function(url){return'https://api.facebook.com/method/links.getStats?'+ module.addQueryStrings({'urls':url,'format':'json'});}};module.googleplus={extract:module.extractUrl,getUrl:function(data){return"https://plus.google.com/share?"+ module.addQueryStrings({'url':data.url});}};module.linkedin={extract:function(that){return{'url':module.checkForUrl(that),'title':module.getAttr(that,'st-share-title'),'summary':module.getAttr(that,'st-share-summary'),'source':module.getAttr(that,'st-share-source')};},getUrl:function(data){return'http://www.linkedin.com/shareArticle?'+ module.addQueryStrings({'mini':'true','url':data.url,'title':data.title,'summary':data.summary,'source':data.source});}};module.pinterest={extract:function(that){return{'url':module.checkForUrl(that),'image':module.getAttr(that,'st-share-image'),'description':module.getAttr(that,'st-share-description')};},getUrl:function(data){return"http://www.pinterest.com/pin/create/button/?"+ module.addQueryStrings({'url':data.url,'media':data.image,'description':data.description});}};module.twitter={extract:function(that){return{'url':module.checkForUrl(that),'text':module.getAttr(that,'st-share-title')};},getUrl:function(data){return'https://twitter.com/intent/tweet?'+ module.addQueryStrings({'url':data.url,'text':data.text});}};return module;})(jQuery,window);ST_Share.init();